var mongoose = require('mongoose'),
    Schema = mongoose.Schema;

var siteSchema = new Schema({
    siteId: {type: Date},
    friendlyId: {type: String},
    domain: {type: String},
    name: {type: String},
    logoUrl: {type: String},
    altLogoUrl: {type: Boolean},
    payPalLogoUrl: {type: String},
    iconUrl: {type: String},
    iconBg: {type: String},
    theme: {type: String},
    primaryEmail: {type: String},
    language: {type: String},
    direction: {type: String},
    showSettings: {type: Boolean},
    showLanguages: {type: Boolean},
    showLogin: {type: Boolean},
    showSearch: {type: Boolean},
    payPalId: {type: Date},
    payPalUseSandbox: {type: Boolean},
    welcomeEmail: {type: String},
    isSMTP: {type: Boolean},
    sMTPHost: {type: String},
    sMTPAuth: {type: String},
    sMTPUsername: {type: String},
    sMTPPassword: {type: String},
    sMTPPasswordIV: {type: String},
    sMTPSecure: {type: String},
    formPrivateId: {type: String},
    formPublicId: {type: String},
    embeddedCodeHead: {type: String},
    embeddedCodeBottom: {type: String},
    status: {type: String},
    plan: {type: String},
    provider: {type: String},
    subscriptionId: {type: String},
    customerId: {type: String},
    canDeploy: {type: Boolean},
    userLimit: {type: String},
    fileLimit: {type: String},
    version: {type: String},
    lastLogin: {type: String},
    created: {type: Date}
});

module.exports = mongoose.model('Site', siteSchema);
